title = "Samuel Åkesson"
description = "Min personliga hemsida / portfolio."
default_language = "sv"

base_url = "/"
minify_html = true
compile_sass = true
build_search_index = false

generate_feeds = true
author = "Samuel Åkesson"

[markdown]
error_on_missing_highlight = true
external_links_target_blank = true
lazy_async_image = true

[slugify]
paths_keep_dates = true

[extra]
keywords = [
	"samuel",
	"åkesson",
	"liu",
	"linköping",
	"lysator",
	"schemgo",
	"undervisningsnummer",
	"un",
	"sermuns",
	"admittansen",
	"zola",
	"ledigt",
]
